export const GET_ALL_POSTS_INIT = "GET_ALL_POSTS_INIT"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR"

export const GET_POST_COMMENTS_INIT = "GET_POST_COMMENTS_INIT"
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS"
export const GET_POST_COMMENTS_ERROR = "GET_POST_COMMENTS_ERROR"


export const SET_POST_COMMENTS = 'SET_POST_COMMENTS'


export const GET_USER_INIT = "GET_USER_INIT"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"